const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('salaryPet', {
  readState: () => ipcRenderer.invoke('state:read'),
  writeState: state => ipcRenderer.invoke('state:write', state),
  updateSettings: patch => ipcRenderer.invoke('state:update-settings', patch),
  updateRuntime: patch => ipcRenderer.invoke('state:update-runtime', patch),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  installDownloadedUpdate: () => ipcRenderer.invoke('updates:install'),
  drag: delta => ipcRenderer.send('window:drag', delta),
  hide: () => ipcRenderer.send('window:hide'),
  openPanel: type => ipcRenderer.send('window:panel', type),
  closePanel: () => ipcRenderer.send('window:close-panel'),
  setAlwaysOnTop: value => ipcRenderer.send('window:set-always-on-top', value),
  setOpacity: value => ipcRenderer.send('window:set-opacity', value),
  setSize: value => ipcRenderer.send('window:set-size', value),
  launchTool: tool => ipcRenderer.invoke('tool:launch', tool),
  pickExecutable: () => ipcRenderer.invoke('tool:pick-executable'),
  pickPetImage: () => ipcRenderer.invoke('pet:pick-image'),
  deletePetImage: id => ipcRenderer.invoke('pet:delete-image', id),
  pickReaderDocument: () => ipcRenderer.invoke('reader:pick-document'),
  restoreToolsPanel: () => ipcRenderer.send('window:restore-tools-panel'),
  openBilibiliHome: () => ipcRenderer.send('window:open-bilibili-home'),
  closeInlinePanel: () => ipcRenderer.send('window:close-inline-panel'),
  resizeInlinePanel: height => ipcRenderer.send('window:resize-inline-panel', height),
  enterWorkMode: () => ipcRenderer.send('pet:enter-work-mode'),
  onToggleWorkMode: callback => ipcRenderer.on('toggle-work-mode', callback),
  onEnterWorkMode: callback => ipcRenderer.on('enter-work-mode', callback),
  onStateUpdated: callback => ipcRenderer.on('state-updated', (_event, state) => callback(state)),
  onUpdateStatus: callback => ipcRenderer.on('update-status', (_event, status) => callback(status)),
  onEmbedBilibili: callback => ipcRenderer.on('panel:embed-bilibili', (_event, payload) => callback(payload)),
  onPetEmbedBilibili: callback => ipcRenderer.on('pet:embed-bilibili', (_event, payload) => callback(payload)),
  onInlineTools: callback => ipcRenderer.on('inline-tools', callback),
  onInlineSettings: callback => ipcRenderer.on('inline-settings', callback),
  onInlineAppearance: callback => ipcRenderer.on('inline-appearance', callback),
  onInlinePanelState: callback => ipcRenderer.on('inline-panel-state', (_event, payload) => callback(payload))
});
